### PR TITLE
covid-19 quick search links in arXiv and bioRxiv/medRxiv

### PR DESCRIPTION
**Pull request by mhl10**
arXiv has decided that we will provide covid-19 quick search links on the home page, both to arXiv and to bioRxiv/medRxiv. 

This is a first pass (see screenshot below). @SBBCornell please reposition or restyle as needed.

Screenshot 2020-03-25 21 25 28

### CODE REVIEW

**Comment by SBBCornell** [comment]
Quick screenshots of the new style commit are below. The styles are somber and in keeping with the old-fashioned look of the homepage.

Screen Shot 2020-03-26 at 9 23 19 AM

Screen Shot 2020-03-26 at 9 23 38 AM

**Comment by mhl10** [comment]
@jimentwood great idea about the short link. I'll add that redirect on beta.arxiv.org

**Comment by mhl10** [comment]
Now updated with https://arxiv.org/covid19search link.

**Comment by mhl10** [comment]
@afromme should we include an additional link to the upcoming blog post, above the news item dated 12 Mar?

**Comment by afromme** [comment]
@mhl10 Yes, definitely, link to the blog post. I'll send you the link when its ready.

@SBBCornell great styles.

**Comment by mhl10** [comment]
@afromme here's the news item. It's dated today but we can update as needed.
Screenshot 2020-03-26 13 42 41

**Pull request merged**
