### PR TITLE
Add CatalyzeX code finder to arXiv Labs

### PR DESCRIPTION
**Pull request by gragtah**
This pull request introduces a new arXiv Labs integration by [CatalyzeX](https://www.catalyzex.com) that finds and links to code implementations for papers.

**Demo:**

https://user-images.githubusercontent.com/978669/217149881-9f62473d-aabd-4cb5-967b-f87017f3d387.mov

### CODE REVIEW

**Comment by gragtah** [comment]
Hi arXiv team, is anything else needed from us here? Please let us know if so, thank you!

**Comment by cbf66** [comment]
Yes. Submit a proposal: [https://arxiv-org.atlassian.net/servicedesk/customer/portal/6](url)

**Comment by gragtah** [comment]
Thanks @cbf66! We've submitted our proposal via that link

**Review by jonathanhyoung — APPROVED** [review]

**Comment by gragtah** [comment]
Hi @jonathanhyoung @cbf66 just wanted to ask what's the status of this integration? We're eagerly looking forward to rolling this out, so please let us know if you have any questions or if there's anything we can help with

**Pull request merged**
