### PR TITLE
Author profile page working wireframe

### PR DESCRIPTION
**Pull request by SBBCornell**
This branch creates a new author profile page in browse and populates it with test content. The layout is responsive and accessible. Preview locally at http://127.0.0.1:5000/author

There is alternate content for logged in users visible by appending to the url: http://127.0.0.1:5000/author?status=loggedin

Logged in user screenshot:
Screen Shot 2020-08-25 at 4 41 12 PM

Screenshot when not logged in:
Screen Shot 2020-08-25 at 4 47 28 PM

### CODE REVIEW

**Comment by jweiskoff** [comment]
There's needed functionality that has been asked for (for years), and this seems like the place to add it. On each of the "papers you own", authors need to be able to recover their paper passwords.

**Comment by SBBCornell** [comment]
> There's needed functionality that has been asked for (for years), and this seems like the place to add it. On each of the "papers you own", authors need to be able to recover their paper passwords.

Thanks for that info!

**Comment by SBBCornell** [comment]
> I really like the design!
> 
> my only comment is that generally speaking the affiliation of an author is considered one of the most important things, so I would put it first (above the email).
> I may even consider using bold or a slightly bigger font for the affiliation, but I leave it to you to decide whether that would look good or not. Otherwise just moving it to the top would be good!

thanks for feedback!

**Comment by SBBCornell** [comment]
Both comments are incorporated into the working wireframe. Screenshots of regular and loggedin displays are included below.

Regular:
Screen Shot 2020-09-01 at 9 10 04 AM

Logged in:
Screen Shot 2020-09-01 at 9 09 27 AM

**Comment by SBBCornell** [comment]
New updates change the displayed content based on the user or profile status. This Miro board shows the different status/states we are considering for both the author profile page and the user account page https://miro.com/app/board/o9J_kmb5NqM=/

/author?status=1 - logged in user looking at their own profile. Screenshot:
Screen Shot 2020-09-08 at 4 54 48 PM



/author?status=2 - a user looking at someone else's existing (ie: "claimed") profile. Screenshot:
Screen Shot 2020-09-08 at 4 55 11 PM



/author?status=3 - a user looking at a non-existent ("unclaimed") profile. Screenshot:
Screen Shot 2020-09-08 at 4 56 34 PM

**Pull request closed without merging**
