### PR TITLE
mobile abs updates - part II

### PR DESCRIPTION
**Pull request by SBBCornell**
This branch is for further mobile-friendly updates to the abs page and a more mobile-friendly header in browse. Changes include:

- Moving the 'download pdf' button below the title and authors, per user feedback (thanks for Martin for that).
- Improved legibility of the 'download' and 'reference' sections.
- Links that are easier to click when using a touch screen.
- Using color and subtle shadows to differentiate sections of the page and break up its length when its a single column.
- Greatly reduced header height on mobile per user feedback. This includes hiding the CU logo on the smallest screen sizes (not cleared with CU branding yet). 
- Added a new menu link to the header with a few quick links. Contents are completely up for discussion.
- The mobile styles pass Cornell's accessibility guidelines.

If the updates have a positive response during testing I recommend we make the same header updates to base as well. 

I added a new js file with a small js script (no dependencies). We can reuse the same script wherever we need an accordion toggle, like the new taxonomy page layout. Let me know if you see any issues with this.

Screenshots of the abs page at phone, tablet, and desktop are below. Note there is only one visible change on desktop: the submission date is moved up above the paper title. 

Screen Shot 2020-03-02 at 3 22 36 PM

Screen Shot 2020-03-02 at 3 22 53 PM

Screen Shot 2020-03-02 at 3 24 43 PM

Screen Shot 2020-03-02 at 3 25 22 PM

Screen Shot 2020-03-02 at 2 56 23 PM

### CODE REVIEW

**Comment by mhl10** [comment]
This looks super. Thinking about branding, I wonder if there's a way to sneak in white "arXiv" text on the red background , while still keeping the rest of the mobile header black.

**Comment by mhl10** [comment]
Looks like the header is clipping the "submitted" line here.
> Screen Shot 2020-03-02 at 3 22 53 PM

**Comment by SBBCornell** [comment]
> Looks like the header is clipping the "submitted" line here.
> 
That screenshot is of the mobile header with the search box toggled open. The other mobile screenshot shows it closed.

**Comment by bdc34** [comment]
I like the download buttons and the reference buttons.

The difference between the header on mobile and non-mobile breaks the continuity of the branding for me.

**Comment by bdc34** [comment]
The INSPIRE HEP button with its "refers to" and "cited by" sort of make the other buttons untidy.  (It sort of does this on desktop pages too)

**Comment by SBBCornell** [comment]
The header is updated with new logos (arXiv and Cornell). The CU logo at phone sizes is just the seal and doesnt follow their guidelines but I will see if we can get an exception. 

The header color is back to red for better continuity with the desktop header. Some quick screenshots are below.

Screen Shot 2020-03-11 at 12 12 56 PM

Screen Shot 2020-03-11 at 12 14 05 PM

Screen Shot 2020-03-11 at 12 13 11 PM

**Comment by mhl10** [comment]
> The header is updated with new logos (arXiv and Cornell). The CU logo at phone sizes is just the seal and doesnt follow their guidelines but I will see if we can get an exception.
> 
> The header color is back to red for better continuity with the desktop header. Some quick screenshots are below.
> 

I love this latest version, and it assuages any concerns I had about branding.

**Comment by SBBCornell** [comment]
The latest updated header is reviewable on the beta server: https://beta.arxiv.org/abs/2003.00017. As before there are no changes to the desktop header, only to the mobile header. Here is a description of what changed:

- We are now using a Cornell logo at phone widths that meets their branding guidelines for web. The previous phone mockups got a "request denied" response from CU branding.
- The header height is a little taller than previous iterations in this branch to accommodate the minimum height of the Cornell seal. It's still much more minimal than what is live now.
- Margins around the Cornell logo are reduced in order to decrease the header height.
- At phone widths the Cornell logo is black to establish the arXiv logo as more prominent in the symbol hierarchy.
- I fixed the error Jim pointed out with the color of the search bar text.
- Please note the one solitary change that affects desktop as well is that the submitted date is now located above the title. I believe this makes sense at all screen widths because that is one of the first pieces of info that users look at to determine if they want to read the article. 

We will be working towards a strong and recognizable logomark that arXiv can use in lieu of the full text logo when we have space constraints, but that is a separate project. For now this mobile header is another incremental improvement.

Screenshots are below for quick reference:

Screen Shot 2020-03-25 at 11 33 34 AM

Screen Shot 2020-03-25 at 11 33 56 AM

**Comment by jweiskoff** [comment]
It might be worth looking at how a paper-id is displayed for a longer classification name (and/or one of the older-style arXiv-ids). Something like [2003.10747](https://arxiv.org/abs/2003.10747) or [cond-mat/0107006](https://arxiv.org/abs/cond-mat/0107006). I chose stat-mech specifically, because it has the longest canonical name of any category.

**Comment by SBBCornell** [comment]
> It might be worth looking at how a paper-id is displayed for a longer classification name (and/or one of the older-style arXiv-ids). Something like [2003.10747](https://arxiv.org/abs/2003.10747) or [cond-mat/0107006](https://arxiv.org/abs/cond-mat/0107006). I chose stat-mech specifically, because it has the longest canonical name of any category.

Thanks for that suggestion. This looks legible to me at narrow widths, would you agree? https://beta.arxiv.org/abs/cond-mat/0107006

**Comment by jweiskoff** [comment]
Yes that looks good to me :)

**Pull request merged**
