### PR TITLE
Fixes bibtex primary class

### PR DESCRIPTION
**Pull request by bdc34**
The `Category` that populates the primaryClass use to subclass `str` but that was changed. That caused this regressio

### CODE REVIEW

**Review by jweiskoff — APPROVED** [review]
lg2m :)

**Comment by collares** [comment]
Many thanks for the quick response! However, there is now a separate bug, which is that the `primaryClass` line does not end with a comma, even though it is not the last line in the entry. Example:

```
@misc{dona2024diameterrandomschreiergraphs,
      title={The diameter of random Schreier graphs}, 
      author={Daniele Dona and Luca Sabatini},
      year={2024},
      eprint={2406.16733},
      archivePrefix={arXiv},
      primaryClass={math.CO}
      url={https://arxiv.org/abs/2406.16733}, 
}
```

**Comment by collares** [comment]
The `doi` entry at https://arxiv.org/bibtex/2403.03279 also looks a bit funny.

**Comment by jweiskoff** [comment]
I just put in [a PR](https://github.com/arXiv/arxiv-browse/pull/647) to fix this.

**Pull request merged**
