### PR TITLE
updates giving week banner

### PR DESCRIPTION
**Pull request by SBBCornell**
This PR is for the Fall 2022 Giving Week banner. 

Devs, could you help Alison and I with two things:
- test view it on dev server
- queue the banner to go live on the morning of Monday October 24th, and stop displaying on the evening of Sunday October 30th.

### CODE REVIEW

**Comment by SBBCornell** [comment]
Interesting question from Alison: "When we had pendo, we put up a "thank you" banner on Saturday morning that also said "it's not too late" and a lot donations came in then. If that's too much trouble, don't worry about it. But if it's relatively easy, having a second banner would be ideal."

I am not aware of an existing mechanism for queueing up different banner content for the weekend but I wanted to ask @bdc34 and @bmaltzan

**Comment by bmaltzan** [comment]
The banner is active on dev: https://dev.arxiv.org/

**Comment by afromme** [comment]
This looks great. Thank you!

**Review by afromme — APPROVED** [review]
Looks great. Thank you!

**Comment by SBBCornell** [comment]
The banner test on dev looks great!

**Comment by bmaltzan** [comment]
> Interesting question from Alison: "When we had pendo, we put up a "thank you" banner on Saturday morning that also said "it's not too late" and a lot donations came in then. If that's too much trouble, don't worry about it. But if it's relatively easy, having a second banner would be ideal."
> 
> I am not aware of an existing mechanism for queueing up different banner content for the weekend but I wanted to ask @bdc34 and @bmaltzan

It doesn't look like we have a mechanism for that. We use a couple of env variables in httpd to check the date range, and then include the user_banner.html file in browse. 
It's a little work to enhance it, but if this would be useful, we should take the time to figure out a set of features that would also be useful for our previous banner deploys. I'm not suggesting a publishing system;)  maybe just file list and rotation rates//.

**Comment by bmaltzan** [comment]
Here's the related PR, that will updates the dates for this banner: https://github.com/arXiv/arxiv-httpd/pull/20

**Review by bmaltzan — APPROVED** [review]

**Review by bdc34 — APPROVED** [review]

**Pull request merged**
