### PR TITLE
Introduce ScienceCast plugin for arXiv Labs

### PR DESCRIPTION
**Pull request by antonfefilov**
This pull request introduces a new [arXiv Labs](https://labs.arxiv.org/) integration that displays links to video casts from [ScienceCast](https://sciencecast.org). It mirrors the implementation used for Hugging Face Spaces demos.

Screenshot:

image

Demo:

https://user-images.githubusercontent.com/1530097/196703119-3eba5f92-8598-4330-a169-ad2ab136b9a1.mov

Running the development environment. From the root of this repository, run:

```
docker build . -t arxiv/browse
docker run -it --publish 8000:8000 arxiv/browse
```

Once the Docker is running:

- go to any paper, e.g. `http://localhost:8000/abs/0704.0988`

- Because none of the dummy dev papers are linked to any cast from ScienceCast, use the "override_paper_id" URL param to override the paper_id used to search for demos, e.g. `http://localhost:8000/abs/0704.0988?override_paper_id=2008.02563`

- Click the Casts tab and open the ScienceCast toggle

### CODE REVIEW

**Comment by antonfefilov** [comment]
Hi arXiv team, is there any progress on this PR?

**Comment by bdc34** [comment]
We are hoping to deploy this the week of the 21st.

--
Brian Caruso
Senior Developer at arXiv

arXiv.org Cornell Tech
***@***.*** ***@***.***>
[cid:077f5804-9b03-4f3e-b275-8fc3d060baed]
________________________________

**Comment by SteinnSigurdsson** [comment]
are we deploying it this week?  SciCast asked if it was still going ahead week of 21st Nov,  they're holding stuff waiting for it

**Comment by bdc34** [comment]
We didn't get to it this week and people are away on vacation. The PR looks good and we can do it next week.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by bdc34 — APPROVED** [review]
@antonfefilov Hi we are going to merge this to develop, then rearrange the tabs a little. The rearrange that we will do will be to rename "Code & Data" to "Code, Data, Media" and put Sciencecast there.

Thanks for the PR.


You don't n

**Pull request merged**
