### PR TITLE
ARXIVNG-5256: remove pendo code

### PR DESCRIPTION
**Pull request by bmaltzan**
Disable geoip and remove analytics demos.

ie: 
arxiv.matomo.cloud
arxivcu.containers.piwik.pro

### CODE REVIEW

**Review by bdc34 — APPROVED** [review]
I think I might have removed the JS from the base.html in a HOTFIX.

**Comment by bmaltzan** [comment]
Looks like there's still content.analytics.arxiv.org (pendo) in arxiv-docs, but that will go away with info.*
I don't see it anywhere else...

**Comment by bmaltzan** [comment]
>

**Comment by bmaltzan** [comment]
> I think I might have removed the JS from the base.html in a HOTFIX.

No problem

**Pull request merged**
