### PR TITLE
ARXIVNG-1918 add four column footer

### PR DESCRIPTION
**Pull request by eawoods**
This implementation only affects browse pages (front, list, category, abs, etc).
Will have a separate implementation for NG-base shortly.

Note: right now the list and front pages don't have the extra space. I chose to not mess with it for now due to other possible layout complications.

## Desktop:
screen shot 2019-03-01 at 11 48 13 am

## Tablet:
screen shot 2019-03-01 at 11 48 30 am

## Mobile:
screen shot 2019-03-01 at 11 48 43 am

### CODE REVIEW

**Comment by erickpeirson** [comment]
@eawoods When I view this locally, I see the four columns, but the spacing relative to the abs content looks the same as what is on production now. Is that intended?

image
image

**Comment by eawoods** [comment]
No - local is not pulling in the new static style sheet changes. Sorry about that - fixing now.

**Comment by eawoods** [comment]
OK @erickpeirson try again - fixed style sheet and took out some padding that was causing issues. Will update screenshots momentarily.

**Comment by mhl10** [comment]
I've updated dependencies in `Pipfile` which will hopefully fix failed tests.

**Comment by mhl10** [comment]
Merging on Liz's behalf per discussion

**Pull request merged**
